CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Email VARCHAR(100) NOT NULL,
	[Password] VARBINARY(64) NOT NULL,
	[ScreenName] VARCHAR(50) NOT NULL, 
    [Salt] VARCHAR(100) NULL
)
